[package]
name = "workboard-cli"
default-run = "workboard"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "workboard"
path = "src/main.rs"

[dependencies]
clap.workspace = true
crossterm.workspace = true
directories.workspace = true
ratatui.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
workboard-application = { path = "../application" }
workboard-core = { path = "../core" }
workboard-daemon = { path = "../daemon" }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
