[package]
name = "workboard-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "workboard_desktop"

[[bin]]
name = "workboard-desktop"
path = "src/main.rs"

[build-dependencies]
ico = "0.5.0"
tauri-build = { version = "2.6.3", features = ["isolation"] }

[dependencies]
directories.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2.11.5", default-features = false, features = ["isolation", "wry"] }
workboard-client = { path = "../../../crates/workboard-client" }
workboard-client-protocol = { path = "../../../crates/workboard-client-protocol" }

[dev-dependencies]
tempfile.workspace = true
tauri = { version = "2.11.5", default-features = false, features = ["isolation", "test"] }
time.workspace = true

[lints]
workspace = true
