[package]
name = "workboard-daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "workboard_daemon"

[dependencies]
clap.workspace = true
notify.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
workboard-application = { path = "../workboard-application" }
workboard-core = { path = "../workboard-core" }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true

