[package]
name = "workboard-cli"
default-run = "workboard"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "workboard"
path = "src/main.rs"

[dependencies]
clap.workspace = true
crossterm.workspace = true
directories.workspace = true
ratatui.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
workboard-application = { path = "../workboard-application" }
workboard-client = { path = "../workboard-client" }
workboard-client-protocol = { path = "../workboard-client-protocol" }
workboard-core = { path = "../workboard-core" }

[dev-dependencies]
rusqlite.workspace = true
tempfile.workspace = true
workboard-daemon = { path = "../workboard-daemon" }

[lints]
workspace = true
